- Boot loader in GAS [link](https://www.codeproject.com/Articles/664165/Writing-a-boot-loader-in-Assembly-and-C-Part)
- GAS vs NASM [link](https://www.ibm.com/developerworks/library/l-gas-nasm/index.html)
- raphical Linux on Windows [link](https://virtualizationreview.com/articles/2017/02/08/graphical-programs-on-windows-subsystem-on-linux.aspx)
